name:           cabal2nix
version:        "3"
synopsis:       Convert Cabal files into Nix build instructions.
author:
  - Peter Simons
  - Andres Loeh
  - Benno Fünfstück
  - Mateusz Kowalczyk
  - Michael Alan Dorman
  - Mathijs Kwik
  - Shea Levy
  - Dmitry Malikov
  - Eric Seidel
  - Hamish Mackenzie
  - Nikolay Amiantov
  - Aycan iRiCAN
  - Bryan Gardiner
  - Joe Hermaszewski
  - John Wiegley
  - Philipp Hausmann
  - Spencer Janssen
  - Tom Hunger
  - William Casarin
  - koral
  - Adam Vogt
  - Alexey Shmalko
  - Corey O'Connor
  - Cray Elliott
  - Felix Kunzmann
  - Gabriel Ebner
  - Gergely Risko
  - Jacob Mitchell
  - Joachim Fasting
  - John Albietz
  - John Chee
  - Jussi Maki
  - Mark Laws
  - Mark Wotton
  - Matthew Stewart
  - Matvey Aksenov
  - Nicolas Rolland
  - Oliver Charles
  - Pascal Wittmann
  - Patrick John Wheeler
  - Profpatsch
  - Raymond Gauthier
  - Renzo Carbonara
  - Rodney Lorrimar
  - Sibi
  - Tanner Doshier
  - Viktar Basharymau
  - danbst
  - karsten gebbert
  - laMudri
  - Александр Цамутали
maintainer:     Peter Simons <simons@cryp.to>
license:        BSD3
license-file:   LICENSE
github:         nixos/cabal2nix
category:       Distribution, Nix
stability:      stable
tested-with:    GHC > 8.2 && < 8.3
description: >
  Convert Cabal files into Nix build instructions. Users of Nix can install the
  latest version by running:

  .

  > nix-env -i cabal2nix

custom-setup:
  dependencies:
    - base >= 4 && <5
    - Cabal
    - cabal-doctest >= 1 && <1.1

ghc-options: -Wall

extra-source-files:
  README.md

dependencies:
  - aeson
  - ansi-wl-pprint
  - base < 5
  - bytestring
  - Cabal > 2
  - containers
  - deepseq >= 1.4
  - directory
  - distribution-nixpkgs >= 1.1
  - filepath
  - hackage-db
  - hopenssl >= 2
  - language-nix
  - lens
  - optparse-applicative
  - pretty >= 1.1.2
  - process
  - split
  - text
  - transformers
  - yaml

executables:
  cabal2nix:
    main:               Main.hs
    source-dirs:        cabal2nix
    other-modules:
      - Paths_cabal2nix
    dependencies:
      - pretty-show
    other-extensions:
      - DeriveGeneric
      - DuplicateRecordFields
      - FlexibleInstances

tests:
  doctests:
    main: doctests.hs
    source-dirs:
      - test
    dependencies:
      - doctest
    ghc-options:
      - -threaded
